<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Projects</title>
</head>
<body>

<?php include __DIR__.'/_menu.php'; ?>

<h1>You're in!</h1>

<p>Well done, you've managed to log in!</p>

</body>
</html>