<?php include __DIR__.'/_header.php'; ?>

<h1>Login page</h1>

<?php if (!empty($messages['info'])): ?>
    <div class="info"><?php echo join('<br/>', $messages['info']); ?></div>
<?php endif; ?>

<form id="login" method="post" action="/login">
    <h4>Sign in <i>Old Skool</i> with your email and password</h4>

    <div class="row">
        <div class="five columns">
            <label for="frmEmail">email address</label>
            <input class="u-full-width" type="email" placeholder="test@example.com" id="frmEmail" name="email">
        </div>
        <div class="five columns">
            <label for="frmPassword">email address</label>
            <input class="u-full-width" type="password" id="frmPassword" name="password">
        </div>
        <div class="two columns">
            <input class="button-primary" type="submit" value="login" />
        </div>
    </div>
    <?php if (!empty($messages['error'])): ?>
    <div class="error"><?php echo join('<br/>', $messages['error']); ?></div>
    <?php endif; ?>
</form>

<form id="login" method="post" action="http://localhost:8020/oauth/google">
    <h4>Sign in <i>Hipster Kool</i> with your Google account</h4>
    <button class="loginBtn loginBtn--google">Login with Google</button>
</form>

<?php
/*
<script>
$('#login').submit(function(e){
    e.preventDefault();
    var $form = $(this);
    $.ajax({
        url: 'http://localhost:8020/authenticate',
        type: 'get',
        dataType: 'json',
        data: $form.serialize(),
        success: function(d) {
            //
            if (d.hasOwnProperty('token') && d.token !== '') {
                //
                $.ajax({
                    url: '/login/' + d.token,
                    type: 'PUT',
                    success: function(result) {
                        location.href = '/projects';
                    },
                    error: function(result) {
                        $('#feedback').html('<p>Token could not be set at this time</p>');
                    }
                });
                //
                console.log('/login/' + d.token);
            } else {
                $('#feedback').html('<p>No token was provided by the authentication service</p>');
            }
            //
        },
        error: function(d) {
            $('#feedback').html('<p>' + d.error + '</p>');
        }
        crossDomain: true
    });
    return false;
});
</script>
*/
?>

<?php include __DIR__.'/_footer.php'; ?>
