<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
</head>
<body>

<h1>Login page</h1>

<form id="login" method="post">
    <h4>Sign in <i>Old Skool</i> with your email and password</h4>
    <div><label>email address<br/><input type="text" name="username" /></label></div>
    <div><label>password<br/><input type="password" name="password" /></label></div>
    <div><input type="submit" /></div>
</form>

</body>
</html>